"""init

Revision ID: a7d06bcee3d2
Revises: 
Create Date: 2026-02-13 19:51:23.320872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7d06bcee3d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('apellido_paterno', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('apellido_materno', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.DATE(), nullable=False),
    sa.Column('contrasena', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('rol', mysql.ENUM('admin', 'usuario'), server_default=sa.text("'usuario'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
